### ISSUE TITLE
[question] boolean overloading to get rid of explicit is_success() or is_error() calls

### ISSUE THREAD

**Issue by XSven** [perlreview/returnvalue#11]
Did you think about boolean overloading of the `ReturnValue` class so that this

```
unless( $result ) {
  ...; # do error stuff
}
```

is possible? To me a true (successful) `$result` would be one without an error. Of course it is possible to invert this view.

PS: Maybe you want to add the [results](https://metacpan.org/pod/results) CPAN module to the SEE ALSO section.

**Comment by briandfoy** [comment]
I'd be open to boolean overloading if you'd like to add it.

If you'd like to add the Results module in a separate PR, I could merge that too.

**Comment by XSven** [comment]
Ok I am not sure if I I want to change to the return-value-based (result-value-based) error handling: The withdrawn (deprecated) [Return::Value](https://metacpan.org/pod/Return::Value) CPAN module for example makes some interesting statements in its DESCRIPTION and
DO NOT USE THIS LIBRARY sections that make me hesitate.

**Comment by XSven** [comment]
I known the current `ReturnValue` types `ReturnValue::Success` and `ReturnValue::Error` are not yet really polymorphic because they have the same attributes and methods but do we known when this will change and what are the consequences?

I am looking for a general Perl error handling strategy and I thought the return-value-based error handling would be such a strategy. Grabbing the code is a good idea especially if this module is a demo module only. Thx.

**Comment by briandfoy** [comment]
I'm not sure what you are looking at for polymorphism. Each class has the same interface, which is the polymorphic bit. But, the objects can contain things behind `values` that are whatever you decide to put in there.

Either way, I'm not planning to change the interface. Even if I did, it would be a major version bump and I'd leave the previous version on CPAN. Tools like `cpanm` (with cpanfile maybe) can install earlier versions.

I'm going to close the issue. Happy to talk about it, but I think now it's up to you to decide if the idea works. Maybe try it out and see how complicated it gets and it seems to fit the problem. If not, try something else. I think it's all about how you want to consume the result of any operation.
